import React from 'react'
import { LockKeyhole, MapPin, Palette, UserRound } from 'lucide-react'
import type { FilmProject } from '@/agent/schemas/filmProjectSchemas'

const Empty: React.FC = () => <div className="flex h-full flex-col items-center justify-center px-8 text-center"><Palette className="h-6 w-6 text-white/18" /><p className="mt-3 text-[11px] font-medium text-white/52">No FilmProject context</p><p className="mt-1 text-[9px] leading-4 text-white/28">The Agent will keep durable project context here instead of burying it in chat.</p></div>

export const AgentContext: React.FC<{ project: FilmProject | null }> = ({ project }) => {
  if (!project) return <Empty />
  return (
    <div className="space-y-4 p-4 text-[10px]">
      <section><div className="flex items-center justify-between"><h3 className="font-semibold text-white/78">{project.title}</h3><span className="rounded-full bg-white/[0.05] px-2 py-1 text-[7px] uppercase tracking-wide text-white/32">{project.status}</span></div><p className="mt-2 leading-4 text-white/48">{project.brief.logline || 'Brief is still being developed.'}</p><div className="mt-3 grid grid-cols-2 gap-2">{[['Genre', project.brief.genre], ['Duration', `${project.brief.targetDurationSec}s`], ['Ratio', project.brief.aspectRatio], ['Platform', project.brief.platform]].map(([label, value]) => <div key={label} className="rounded-xl bg-white/[0.025] px-2.5 py-2"><span className="block text-[7px] uppercase tracking-wide text-white/22">{label}</span><span className="mt-1 block truncate text-[9px] text-white/58">{value || '—'}</span></div>)}</div></section>
      <section className="border-t border-white/[0.06] pt-4"><div className="mb-2 flex items-center gap-2"><Palette className="h-3.5 w-3.5 text-[#B8A8FF]" /><h3 className="font-semibold text-white/70">Style bible</h3></div><p className="leading-4 text-white/42">{project.styleBible.visualIdentity || project.brief.visualStyle || 'No visual identity locked yet.'}</p>{project.styleBible.lockedRules.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{project.styleBible.lockedRules.map((rule) => <span key={rule} className="inline-flex items-center gap-1 rounded-full bg-[#7C5CFF]/10 px-2 py-1 text-[7px] text-[#C8BCFF]/75"><LockKeyhole className="h-2.5 w-2.5" />{rule}</span>)}</div>}</section>
      <section className="border-t border-white/[0.06] pt-4"><div className="mb-2 flex items-center gap-2"><UserRound className="h-3.5 w-3.5 text-[#B8A8FF]" /><h3 className="font-semibold text-white/70">Characters · {project.characters.length}</h3></div><div className="space-y-2">{project.characters.map((character) => <div key={character.id} className="rounded-xl border border-white/[0.06] bg-white/[0.018] p-2.5"><div className="flex items-center justify-between"><p className="font-medium text-white/68">{character.name}</p><span className="text-[7px] text-white/25">{character.role}</span></div><p className="mt-1.5 line-clamp-3 leading-4 text-white/38">{character.appearance}</p>{character.lockedTraits.length > 0 && <p className="mt-2 flex items-center gap-1 text-[7px] text-[#B8A8FF]/65"><LockKeyhole className="h-2.5 w-2.5" /> {character.lockedTraits.join(' · ')}</p>}</div>)}</div></section>
      <section className="border-t border-white/[0.06] pt-4"><div className="mb-2 flex items-center gap-2"><MapPin className="h-3.5 w-3.5 text-[#B8A8FF]" /><h3 className="font-semibold text-white/70">Locations · {project.locations.length}</h3></div><div className="space-y-2">{project.locations.map((location) => <div key={location.id} className="rounded-xl border border-white/[0.06] bg-white/[0.018] p-2.5"><p className="font-medium text-white/68">{location.name}</p><p className="mt-1.5 line-clamp-3 leading-4 text-white/38">{location.description}</p></div>)}</div></section>
    </div>
  )
}
